[theme]
base = "dark"
primaryColor = "#f5a623"
backgroundColor = "#020c18"
secondaryBackgroundColor = "#040f20"
textColor = "#c8cdd4"
font = "monospace"

[server]
headless = true

[browser]
gatherUsageStats = false
